### ISSUE TITLE
Selected aspect ratio not respected on front end of site

### ISSUE THREAD

**Issue by LevinMedia** [LevinMedia/figma-embed-block#14]
Certain themes (Tested on twenty twenty, and twenty nineteen) don't respect the aspect ratio controls in the block setting. For example, both blocks on this page are set to "Landscape" - and they stretch to a seemingly random height. 

![screencapture-nervous-hippopotamus-jurassic-ninja-2019-12-04-figma-embed-2019-12-04-12_30_00](https://user-images.githubusercontent.com/4500952/70178977-07caf800-1692-11ea-81ac-86859505e861.png)

For contrast, the same blocks respect the aspect ratio when using the storefront theme

![screencapture-nervous-hippopotamus-jurassic-ninja-2019-12-04-figma-embed-2019-12-04-12_32_52](https://user-images.githubusercontent.com/4500952/70179073-38ab2d00-1692-11ea-8a44-89b25b33ada9.png)

**Comment by jameslnewell** [comment]
Instead of using a fixed width container to constrain the width of `.entry-content`, the theme adds `max-width` to each of the immediate `.entry-content` children.

![image](https://user-images.githubusercontent.com/2237996/70183023-1b7d6980-1739-11ea-86fa-8c01d8655d41.png)

This means the width is constrained to `58em` putting the aspect ratio out since the height (defined via padding) is based off the width of the parent container.

**Comment by jameslnewell** [comment]
There also seems to be a width/height set by the theme:

![image](https://user-images.githubusercontent.com/2237996/70184114-4b2d7100-173b-11ea-8348-848d58cef1f7.png)
